name: apiverve_airportdistance
description: Airport Distance is a simple tool for getting the distance between two airports. It returns the distance between the two airports.
version: 1.1.13
homepage: https://airportdistance.apiverve.com?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/airportdistance-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
